name: flutter_blue_plus_platform_interface
description: A common platform interface for the flutter_blue_plus plugin.
version: 1.0.0
homepage: https://github.com/tnc1997/flutter-blue-plus

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
